name: project

on: push

env:
  SSH_HOST: 109.71.242.118
  SSH_PORT: 22
  SSH_USER: ilya
  SSH_KEY: ${{ secrets.TIMEWEB2 }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    env:
      WORKDIR: /var/www/ilya/data/www/aalyans74.ru
      BUILD_DIR: /var/www/ilya/data/www/aalyans74.ru_build
      ENV_FILE: /var/www/ilya/data/www/build/.env.shop.frontend.dev
      APP_NAME: aalyans74.ru-app

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.SSH_HOST }}
        port: ${{ env.SSH_PORT }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        source: ./*, !.gitignore, !.github, !.git, !.gitattributes, !./docker, !./docker-compose.yml, !./node_modules, !./vendor, !./resources/admin/.env
        target: ${{ env.BUILD_DIR }}

    - name: SSH run remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SSH_HOST }}
        port: ${{ env.SSH_PORT }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        script: |
          cd ${{ env.BUILD_DIR }}
          cp ${{ env.ENV_FILE }} ./.env
          npm install
          npm run build
          
          pm2 delete ${{ env.APP_NAME }}
          rm -rf ${{ env.WORKDIR }}
          mv ${{ env.BUILD_DIR }} ${{ env.WORKDIR }}
          cd ${{ env.WORKDIR }}
          pm2 start npm --name ${{ env.APP_NAME }} -- run start:dev
          pm2 save

  deploy-master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    env:
      WORKDIR: /var/www/ilya/data/www/aalyans.ru
      BUILD_DIR: /var/www/ilya/data/www/aalyans.ru_build
      ENV_FILE: /var/www/ilya/data/www/build/.env.shop.frontend.prod
      APP_NAME: aalyans.ru-app

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SSH_HOST }}
          port: ${{ env.SSH_PORT }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          source: ./*, !.gitignore, !.github, !.git, !.gitattributes, !./docker, !./docker-compose.yml, !./node_modules, !./vendor, !./resources/admin/.env
          target: ${{ env.BUILD_DIR }}

      - name: SSH run remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          port: ${{ env.SSH_PORT }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            cd ${{ env.BUILD_DIR }}
            cp ${{ env.ENV_FILE }} ./.env
            npm install
            npm run build
            
            pm2 delete ${{ env.APP_NAME }}
            rm -rf ${{ env.WORKDIR }}
            mv ${{ env.BUILD_DIR }} ${{ env.WORKDIR }}
            cd ${{ env.WORKDIR }}
            pm2 start npm --name ${{ env.APP_NAME }} -- run start:prod
            pm2 save